<?php
/**
 * AccountDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Catapult REST Endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.19
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AccountDTO Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccountDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AccountDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'address' => 'string',
        'address_height' => 'string',
        'public_key' => 'string',
        'public_key_height' => 'string',
        'account_type' => '\OpenAPI\Client\Model\AccountTypeEnum',
        'linked_account_key' => 'string',
        'activity_buckets' => '\OpenAPI\Client\Model\ActivityBucketDTO[]',
        'mosaics' => '\OpenAPI\Client\Model\Mosaic[]',
        'importance' => 'string',
        'importance_height' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'address' => null,
        'address_height' => null,
        'public_key' => null,
        'public_key_height' => null,
        'account_type' => null,
        'linked_account_key' => null,
        'activity_buckets' => null,
        'mosaics' => null,
        'importance' => null,
        'importance_height' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'address' => 'address',
        'address_height' => 'addressHeight',
        'public_key' => 'publicKey',
        'public_key_height' => 'publicKeyHeight',
        'account_type' => 'accountType',
        'linked_account_key' => 'linkedAccountKey',
        'activity_buckets' => 'activityBuckets',
        'mosaics' => 'mosaics',
        'importance' => 'importance',
        'importance_height' => 'importanceHeight'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'address' => 'setAddress',
        'address_height' => 'setAddressHeight',
        'public_key' => 'setPublicKey',
        'public_key_height' => 'setPublicKeyHeight',
        'account_type' => 'setAccountType',
        'linked_account_key' => 'setLinkedAccountKey',
        'activity_buckets' => 'setActivityBuckets',
        'mosaics' => 'setMosaics',
        'importance' => 'setImportance',
        'importance_height' => 'setImportanceHeight'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'address' => 'getAddress',
        'address_height' => 'getAddressHeight',
        'public_key' => 'getPublicKey',
        'public_key_height' => 'getPublicKeyHeight',
        'account_type' => 'getAccountType',
        'linked_account_key' => 'getLinkedAccountKey',
        'activity_buckets' => 'getActivityBuckets',
        'mosaics' => 'getMosaics',
        'importance' => 'getImportance',
        'importance_height' => 'getImportanceHeight'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['address'] = isset($data['address']) ? $data['address'] : null;
        $this->container['address_height'] = isset($data['address_height']) ? $data['address_height'] : null;
        $this->container['public_key'] = isset($data['public_key']) ? $data['public_key'] : null;
        $this->container['public_key_height'] = isset($data['public_key_height']) ? $data['public_key_height'] : null;
        $this->container['account_type'] = isset($data['account_type']) ? $data['account_type'] : null;
        $this->container['linked_account_key'] = isset($data['linked_account_key']) ? $data['linked_account_key'] : null;
        $this->container['activity_buckets'] = isset($data['activity_buckets']) ? $data['activity_buckets'] : null;
        $this->container['mosaics'] = isset($data['mosaics']) ? $data['mosaics'] : null;
        $this->container['importance'] = isset($data['importance']) ? $data['importance'] : null;
        $this->container['importance_height'] = isset($data['importance_height']) ? $data['importance_height'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['address'] === null) {
            $invalidProperties[] = "'address' can't be null";
        }
        if ($this->container['address_height'] === null) {
            $invalidProperties[] = "'address_height' can't be null";
        }
        if ($this->container['public_key'] === null) {
            $invalidProperties[] = "'public_key' can't be null";
        }
        if ($this->container['public_key_height'] === null) {
            $invalidProperties[] = "'public_key_height' can't be null";
        }
        if ($this->container['account_type'] === null) {
            $invalidProperties[] = "'account_type' can't be null";
        }
        if ($this->container['linked_account_key'] === null) {
            $invalidProperties[] = "'linked_account_key' can't be null";
        }
        if ($this->container['activity_buckets'] === null) {
            $invalidProperties[] = "'activity_buckets' can't be null";
        }
        if ($this->container['mosaics'] === null) {
            $invalidProperties[] = "'mosaics' can't be null";
        }
        if ($this->container['importance'] === null) {
            $invalidProperties[] = "'importance' can't be null";
        }
        if ($this->container['importance_height'] === null) {
            $invalidProperties[] = "'importance_height' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets address
     *
     * @return string
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string $address Decoded address.
     *
     * @return $this
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets address_height
     *
     * @return string
     */
    public function getAddressHeight()
    {
        return $this->container['address_height'];
    }

    /**
     * Sets address_height
     *
     * @param string $address_height Height of the blockchain.
     *
     * @return $this
     */
    public function setAddressHeight($address_height)
    {
        $this->container['address_height'] = $address_height;

        return $this;
    }

    /**
     * Gets public_key
     *
     * @return string
     */
    public function getPublicKey()
    {
        return $this->container['public_key'];
    }

    /**
     * Sets public_key
     *
     * @param string $public_key public_key
     *
     * @return $this
     */
    public function setPublicKey($public_key)
    {
        $this->container['public_key'] = $public_key;

        return $this;
    }

    /**
     * Gets public_key_height
     *
     * @return string
     */
    public function getPublicKeyHeight()
    {
        return $this->container['public_key_height'];
    }

    /**
     * Sets public_key_height
     *
     * @param string $public_key_height Height of the blockchain.
     *
     * @return $this
     */
    public function setPublicKeyHeight($public_key_height)
    {
        $this->container['public_key_height'] = $public_key_height;

        return $this;
    }

    /**
     * Gets account_type
     *
     * @return \OpenAPI\Client\Model\AccountTypeEnum
     */
    public function getAccountType()
    {
        return $this->container['account_type'];
    }

    /**
     * Sets account_type
     *
     * @param \OpenAPI\Client\Model\AccountTypeEnum $account_type account_type
     *
     * @return $this
     */
    public function setAccountType($account_type)
    {
        $this->container['account_type'] = $account_type;

        return $this;
    }

    /**
     * Gets linked_account_key
     *
     * @return string
     */
    public function getLinkedAccountKey()
    {
        return $this->container['linked_account_key'];
    }

    /**
     * Sets linked_account_key
     *
     * @param string $linked_account_key linked_account_key
     *
     * @return $this
     */
    public function setLinkedAccountKey($linked_account_key)
    {
        $this->container['linked_account_key'] = $linked_account_key;

        return $this;
    }

    /**
     * Gets activity_buckets
     *
     * @return \OpenAPI\Client\Model\ActivityBucketDTO[]
     */
    public function getActivityBuckets()
    {
        return $this->container['activity_buckets'];
    }

    /**
     * Sets activity_buckets
     *
     * @param \OpenAPI\Client\Model\ActivityBucketDTO[] $activity_buckets activity_buckets
     *
     * @return $this
     */
    public function setActivityBuckets($activity_buckets)
    {
        $this->container['activity_buckets'] = $activity_buckets;

        return $this;
    }

    /**
     * Gets mosaics
     *
     * @return \OpenAPI\Client\Model\Mosaic[]
     */
    public function getMosaics()
    {
        return $this->container['mosaics'];
    }

    /**
     * Sets mosaics
     *
     * @param \OpenAPI\Client\Model\Mosaic[] $mosaics Mosaic units owned. The amount is represented in absolute amount. Thus a balance of 123456789 for a mosaic with divisibility 6 (absolute) means the account owns 123.456789.
     *
     * @return $this
     */
    public function setMosaics($mosaics)
    {
        $this->container['mosaics'] = $mosaics;

        return $this;
    }

    /**
     * Gets importance
     *
     * @return string
     */
    public function getImportance()
    {
        return $this->container['importance'];
    }

    /**
     * Sets importance
     *
     * @param string $importance Probability of an account to harvest the next block.
     *
     * @return $this
     */
    public function setImportance($importance)
    {
        $this->container['importance'] = $importance;

        return $this;
    }

    /**
     * Gets importance_height
     *
     * @return string
     */
    public function getImportanceHeight()
    {
        return $this->container['importance_height'];
    }

    /**
     * Sets importance_height
     *
     * @param string $importance_height Height of the blockchain.
     *
     * @return $this
     */
    public function setImportanceHeight($importance_height)
    {
        $this->container['importance_height'] = $importance_height;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


