/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Catapult REST Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class StorageInfoDTO {
    /**
    * The number of blocks stored.
    */
    'num_blocks': int;
    /**
    * The number of transactions stored.
    */
    'num_transactions': int;
    /**
    * The number of accounts created.
    */
    'num_accounts': int;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "num_blocks",
            "baseName": "numBlocks",
            "type": "int"
        },
        {
            "name": "num_transactions",
            "baseName": "numTransactions",
            "type": "int"
        },
        {
            "name": "num_accounts",
            "baseName": "numAccounts",
            "type": "int"
        }    ];

    static getAttributeTypeMap() {
        return StorageInfoDTO.attributeTypeMap;
    }
}

