<?php 

namespace NEM\Models\Transaction;

class CosignatureSignedTransaction {
    /**
     * @param parentHash
     * @param signature
     * @param signer
     */
    public $parentHash;
    public $signature;
    public $signer;
    function __construct(
                /**
                 * The hash of parent aggregate transaction that has been signed by a cosignatory of the transaction
                 */
                string $parentHash,
                /**
                 * The signatures generated by signing the parent aggregate transaction hash.
                 */
                string $signature,
                /**
                 * The signer of the transaction.
                 */
                string $signer) {
    	$this->parentHash = $parentHash;
    	$this->signature = $signature;
    	$this->signer = $signer;

    }
}